In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## create and read 

#### 1D array

In [3]:
arr1 = np.array([1,2,3,4,5,6])

In [4]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape


(6,)

In [7]:
arr1.dtype


dtype('int64')

In [8]:
arr1.ndim


1

In [9]:
arr1.size

6

#### 2d array

In [10]:
arr2=np.array([[1,4,5],[6,7,4]])


In [11]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape # (row,column)

(2, 3)

In [14]:
arr2.dtype


dtype('int64')

In [15]:
arr2.size

6

#### 3D array

In [16]:
arr3=np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]],[[3,7,9],[4,10,11]]])
    

In [17]:
arr3

array([[[ 1,  4,  5],
        [ 6,  7,  4]],

       [[ 3,  5,  4],
        [ 5,  8,  7]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

In [18]:
arr3.ndim


3

In [19]:
arr3.shape

(3, 2, 3)

In [20]:
arr3.size

18

## Create random array 

In [21]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.46039441, 0.35284027, 0.47522963],
        [0.15469256, 0.98569105, 0.17212917]],

       [[0.43131704, 0.96721089, 0.34374773],
        [0.23267138, 0.52105739, 0.56626124]],

       [[0.46978742, 0.39199381, 0.32652764],
        [0.2287671 , 0.5904688 , 0.11782486]]])

In [22]:
randomArr.dtype


dtype('float64')

In [23]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
zeroes.ndim

3

In [25]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [26]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
arr3

array([[[ 1,  4,  5],
        [ 6,  7,  4]],

       [[ 3,  5,  4],
        [ 5,  8,  7]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

In [28]:
int(arr3[0][0][2])

5

In [29]:
arr3[2]

array([[ 3,  7,  9],
       [ 4, 10, 11]])

In [30]:
int(arr3[1][0][1])

5

In [31]:
int(arr3[1,0,1])

5

## update and delete

In [32]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)


In [33]:
a1

array([[[0.48903645, 0.44494629],
        [0.91260949, 0.55388912],
        [0.92440447, 0.50726267]],

       [[0.35447767, 0.43533847],
        [0.28116736, 0.66960137],
        [0.00203121, 0.78149027]]])

In [34]:
a2

array([[[0.84786795, 0.75940016],
        [0.27657209, 0.47963567],
        [0.54320388, 0.28614953]],

       [[0.21988466, 0.17006685],
        [0.05407895, 0.42331479],
        [0.08591418, 0.36948533]]])

### basic math operations

In [35]:
np.add(a1,a2)

array([[[1.3369044 , 1.20434645],
        [1.18918158, 1.03352479],
        [1.46760835, 0.7934122 ]],

       [[0.57436233, 0.60540532],
        [0.33524631, 1.09291616],
        [0.08794539, 1.1509756 ]]])

In [36]:
np.subtract(a1,a2)

array([[[-0.3588315 , -0.31445387],
        [ 0.63603739,  0.07425345],
        [ 0.38120059,  0.22111314]],

       [[ 0.13459301,  0.26527162],
        [ 0.22708841,  0.24628658],
        [-0.08388297,  0.41200493]]])

In [37]:
np.divide(a1,a2)

array([[[0.57678374, 0.58591809],
        [3.29971643, 1.15481219],
        [1.70176338, 1.77271889]],

       [[1.61210735, 2.55980791],
        [5.19920171, 1.58180481],
        [0.02364231, 2.11507792]]])

In [38]:
np.multiply(a1,a2)

array([[[4.14638334e-01, 3.37892285e-01],
        [2.52402317e-01, 2.65664980e-01],
        [5.02140096e-01, 1.45152974e-01]],

       [[7.79442010e-02, 7.40366427e-02],
        [1.52052350e-02, 2.83452161e-01],
        [1.74509696e-04, 2.88749190e-01]]])

### statistical operations

In [39]:
sqrt = int(np.sqrt(25))
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)
             

In [40]:
sqrt

5

In [41]:
abs

np.int64(2)

In [42]:
power

np.int64(256)

In [43]:
log


np.float64(3.2188758248682006)

In [44]:
mins

np.float64(0.002031209379582455)

In [45]:
maxs

np.float64(0.8478679540062916)

### update the values

In [46]:
arr3


array([[[ 1,  4,  5],
        [ 6,  7,  4]],

       [[ 3,  5,  4],
        [ 5,  8,  7]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

In [47]:
arr3[0,0,2] = 50
arr3

array([[[ 1,  4, 50],
        [ 6,  7,  4]],

       [[ 3,  5,  4],
        [ 5,  8,  7]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

In [48]:
arr3.sort()
arr3

array([[[ 1,  4, 50],
        [ 4,  6,  7]],

       [[ 3,  4,  5],
        [ 5,  7,  8]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

### reshape

In [49]:
arr3.shape
arr3

array([[[ 1,  4, 50],
        [ 4,  6,  7]],

       [[ 3,  4,  5],
        [ 5,  7,  8]],

       [[ 3,  7,  9],
        [ 4, 10, 11]]])

In [50]:
arr3.shape

(3, 2, 3)

In [51]:
arr3_reshape = arr3.reshape((2,3,-1))
arr3_reshape

array([[[ 1,  4, 50],
        [ 4,  6,  7],
        [ 3,  4,  5]],

       [[ 5,  7,  8],
        [ 3,  7,  9],
        [ 4, 10, 11]]])

In [52]:
arr3_reshape.shape

(2, 3, 3)

## updating and inserting

In [53]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
#create a new array 
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
apen = np.append(zeroes,new_array,axis=0) # axis 0 is row axis 1 is column
apen

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
#Insert

In [57]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
inserted_array = np.insert(zeroes,1,new_array,axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [60]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.61470978, 0.96511041, 0.38789169],
        [0.66560292, 0.20033356, 0.61535523]],

       [[0.01394222, 0.29614939, 0.65428308],
        [0.5694473 , 0.21685705, 0.43504833]],

       [[0.86479484, 0.53242738, 0.75608732],
        [0.19773032, 0.08008497, 0.74884746]]])

In [61]:
#delete the array
arr5 = np.delete(arr4,0,axis=1)

In [62]:
arr5

array([[[0.66560292, 0.20033356, 0.61535523]],

       [[0.5694473 , 0.21685705, 0.43504833]],

       [[0.19773032, 0.08008497, 0.74884746]]])

In [63]:
np.save('New_array',arr5) # name of the file and which array should we store

## Load the file 

In [65]:
np.load('New_array.npy')

array([[[0.66560292, 0.20033356, 0.61535523]],

       [[0.5694473 , 0.21685705, 0.43504833]],

       [[0.19773032, 0.08008497, 0.74884746]]])